---
title: "Lab 2 Assignment: Group 16"
format:
  html:
    embed-resources: true
editor: visual
---

Group 16: Konstantina Gkopi(s243692), Eric Torres (s243275), Lucía de Lamadrid (s243311), Jorge Santiago (s24), Elena Iriondo (s243312)

#### **T7: Like T6, but with densitograms** GROUP ASSIGNMENT

We first have to load the .RData file, which contains a tibble with the results of the genomic hybridisation array. We also load the library *tidyverse* and set a seed, so that our results can be reproducible. 

```{r}
load("data/gravier.RData")
```

```{r}
library("tidyverse")
```

```{r}
set.seed(676571)
cancer_data=mutate(as_tibble(pluck(gravier,"x")),y=pluck(gravier,"y"),pt_id=1:length(pluck(gravier, "y")),age=round(rnorm(length(pluck(gravier,"y")),mean=55,sd=10),1))
cancer_data=rename(cancer_data,event_label=y)
cancer_data$age_group=cut(cancer_data$age,breaks=seq(10,100,by=10))
cancer_data=relocate(cancer_data,c(pt_id,age,age_group,pt_id,event_label))
```

```{r}
ggplot(cancer_data, aes(x=g2E09))+
  geom_density(aes(color = event_label))+
  labs(
    title = "Densitogram of the gene g2E09 based on prognosis in T1T2 node-negative breast cancer patients",
    x = "Expression level of g2E09 (log2 transformed)",
    y = "Density",
    subtitle = "Stratifies on labelling: good = no event, poor = early metastasis",
    caption = "Data from Gravier et al.(2010)",
    color = "Label"
  )+
  theme(legend.position = "bottom", plot.title = element_text(size=11), plot.subtitle = element_text(size=9))
```

```{r}
#| fig-width: 10
#| fig-asp: 0.618
#| out-width: 90%
#| fig-align: center
ggplot(cancer_data, aes(x=g2E09))+
  geom_density(aes(color = event_label))+
  labs(
    title= "Densitogram of the gene g2E09 based on prognosis in T1T2 node-negative breast cancer patients",
    x = "Expression level of g2E09 (log2 transformed)",
    y = "Density",
    subtitle = "Stratifies on labelling: good = no event, poor = early metastasis",
    caption = "Data from Gravier et al.(2010)",
    color = "Label"
  )+
  theme(legend.position = "bottom")
```
